influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  volumes:
    - monitoring:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - grafana:/var/lib/grafana

iot-collector:
  image: wjglerum/iot-collector:latest
  container_name: iot-collector
  ports:
    - "9000:9000"
  env_file:
    - docker.env
  links:
    - influxdb
